---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemoapp
  labels:
    app: mydemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemoapp
  template:
    metadata:
      labels:
        app: mydemoapp
    spec:
      containers:
      - name: mydempapp
        image: sandipmishra/k8sdemo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mydemoapp
spec:
  type: LoadBalancer
  selector:
    app: mydemoapp
  ports:
    - protocol: TCP
      port: 5602
      targetPort: 8080
